voorbeeldproject/config/routes.rb
Rails.application.routes.draw do
  root to: "orders#index"

  resources :orders
end

voorbeeldproject/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

voorbeeldproject/app/models/order.rb
class Order < ApplicationRecord

  validates :name, presence: true

  has_many :orderlines, dependent: :destroy
  accepts_nested_attributes_for :orderlines, reject_if: :all_blank

  def total
    orderlines.collect{ |orderline| orderline.price * orderline.quantity }.sum
  end
end

voorbeeldproject/app/models/orderline.rb
class Orderline < ApplicationRecord
  validates :product_name, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0}
  belongs_to :order
end

voorbeeldproject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  private

  def set_locale
    I18n.locale = :nl
  end
end

voorbeeldproject/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
    5.times { @order.orderlines.build }
  end

  def create
    @order = Order.new order_params
    if @order.save
      flash[:notice] = t("order_created")
      redirect_to orders_path
    else
      render "new"
    end
  end

  def show
    @order = Order.find params[:id]
  end

  def edit
    @order = Order.find params[:id]
  end

  def update
    @order = Order.find params[:id]
    if @order.update_attributes order_params
      flash[:notice] = t("order_updated")
      redirect_to order_path(@order)
    else
      render "edit"
    end
  end

  def destroy
    @order = Order.find params[:id]
    @order.destroy
    flash[:notice] = t("order_deleted")
    redirect_to orders_path
  end

  protected

  def order_params
    params.require(:order).permit(:name, orderlines_attributes: [:id, :product_name, :price, :quantity])
  end
end

voorbeeldproject/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_notice
    flash[:notice]
  end
end

voorbeeldproject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("order_application")%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-warning">
          <%= flash_notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

voorbeeldproject/app/views/orders/_form.html.haml
%h1= t("order")
= f.input :name

%h2=t("orderlines")
= f.simple_fields_for :orderlines do |orderline|
  = orderline.input :product_name
  = orderline.input :price
  = orderline.input :quantity, collection: 0..9
  %hr
= f.submit

voorbeeldproject/app/views/orders/edit.html.haml
= simple_form_for @order, html: { class: 'form-inline' } do |f|
  = render "form", f: f

voorbeeldproject/app/views/orders/index.html.haml
= link_to t("new_order"), new_order_path, method: :get

- if @orders.present?
  %table
    %tr
      %th ID
      %th= t("name")
      %th
    - @orders.each do |order|
      %tr
        %td= OrderDecorator.new(order).id
        %td= order.name
        %td
          = link_to t("show_order"), order_path(order)
- else
  %div= t("no_orders")

voorbeeldproject/app/views/orders/new.html.haml
= simple_form_for @order, html: { class: 'form-inline' } do |f|
  = render "form", f: f

voorbeeldproject/app/views/orders/show.html.haml
%h1= t("header.order", order_id: @order.id)
%sup= t("order_total", total: OrderDecorator.new(@order).total)

%table
  %tr
    %th= t("name")
    %th= t("total")
    %th
  %tr
    %td= @order.name
    %td= OrderDecorator.new(@order).total
    %td
      = link_to t("edit_order"), edit_order_path(@order)
      = link_to t("delete_order"), order_path(@order), method: :delete

  %table
    %tr
      %th= t("name")
      %th= t("price")
      %th= t("quantity")
    - @order.orderlines.each do |orderline|
      %tr
        %td= orderline.product_name
        %td= OrderlineDecorator.new(orderline).price
        %td= OrderlineDecorator.new(orderline).quantity